import axios from 'axios';

axios.defaults.baseURL = 'https://scannarserver.herokuapp.com/api';
axios.interceptors.request.use(
	function(options) {
		options.headers.authorization = localStorage.getItem('token');

		return options;
	},
	function(error) {
		return Promise.reject(error);
	},
);

export {
	GETTING_PRODUCTS,
	GETTING_PRODUCTS_SUCCESSFUL,
	GETTING_PRODUCTS_FAILURE,
	ADDING_PRODUCT,
	ADDING_PRODUCT_SUCCESSFUL,
	ADDING_PRODUCT_FAILURE,
	DELETING_PRODUCT,
	DELETING_PRODUCT_SUCCESSFUL,
	DELETING_PRODUCT_FAILURE,
	EDITING_PRODUCT,
	EDITING_PRODUCT_SUCCESSFUL,
	EDITING_PRODUCT_FAILURE,
} from '../productActions';

export {
	GETTING_SHIPMENTS,
	GETTING_SHIPMENTS_SUCCESSFUL,
	GETTING_SHIPMENTS_FAILURE,
	ADDING_SHIPMENT,
	ADDING_SHIPMENT_SUCCESSFUL,
	ADDING_SHIPMENT_FAILURE,
} from '../shipmentActions';

export {
	USER_REGISTERING,
	USER_REGISTER_SUCCESSFUL,
	USER_REGISTER_FAILURE,
	USER_LOGGING_IN,
	USER_LOGIN_SUCCESSFUL,
	USER_LOGIN_FAILURE,
	USER_LOGGING_OUT,
	USER_LOGOUT_SUCCESSFUL,
	AUTHENTICATING_USER,
	AUTH_SUCCESSFUL,
	AUTH_FAILURE,
	GETTING_ACCOUNT,
	GETTING_ACCOUNT_SUCCESSFUL,
	GETTING_ACCOUNT_FAILURE,
} from '../userActions';
